### ISSUE TITLE
Running Server Doesn't get side panel

### ISSUE THREAD

**Issue by idkjs** [howtographql/react-urql#2]
This is what you get when you run `yarn start` in the server.

<img width="1135" alt="Screenshot 2019-09-03 at 10 52 14 AM" src="https://user-images.githubusercontent.com/2370391/64184093-f119c880-ce38-11e9-88d0-3ecedc76bf0c.png">

Is there some setup to get the side panel?

**Comment by JoviDeCroock** [comment]
If you're talking about the side panel to explore your schema it should come up if you click `docs` on the right.

**Comment by idkjs** [comment]
I'm talking about getting this screen:https://camo.githubusercontent.com/93d8f4ab24d8453f0bd9df94965b4f1eb806ab76/68747470733a2f2f696d6775722e636f6d2f563168703449442e706e67 from the docs.

**Comment by idkjs** [comment]
I am guessing that is preventing me from running the mutations since later it says "Copy the following two mutations into the editor pane - make sure to have the default Playground from the app project selected in the left side-menu:" and that panel is not there to be selected.

**Comment by JoviDeCroock** [comment]
The mutations are now fixed on the current master, about the left-side panel that's a feature of the desktop application seemingly.

**Comment by idkjs** [comment]
Thanks. I hacked around it with,
`test.js`
```
const { prisma } = require('./generated/prisma-client')

// A `main` function so that we can use async/await
async function main() {
  // Create a new link
  const newLink = await prisma.createLink({ description: "Prisma turns your database into a GraphQL API 😎",
  url: "https://www.prismagraphql.com" })
  console.log(`Created new link: ${newLink.url} (ID: ${newLink.id})`)
  const urqlLink = await prisma.createLink({ description: "The best GraphQL client for React",
  url: "https://github.com/FormidableLabs/urql"})
  console.log(`Created new link: ${urqlLink.url} (ID: ${urqlLink.id})`)
}

main().catch(e => console.error(e))
```

showed in app and graphiql
